# Name of our workflow which will act as an identifier when have multilple workflows.
name: Firebase CI/CD

# Define trigger point, on push on master branch, this workflow will be triggered.
on:
  push:
    branches: [ master ]

# The job(s) you want to do when the workflow is triggered
# We will be using an ubuntu-latest virtual machine to perform these processes
jobs:

  build-distribute-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Get the latst dependencies
      - run: flutter pub get
      
      # Build (fat) APK
      # - run: flutter analyze .
      - run: flutter build apk
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks
      
      # Step to Submit the generated APK to Firebase App Distribution
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APPID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: all-testers
          file: build/app/outputs/flutter-apk/app-release.apk