name: CI
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build debug
        run: ./gradlew assembleDevDebug
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:1008843271805:android:d3d75dded9f63801ff4b14
          token: 1//03JMF3_pdbhQxCgYIARAAGAMSNwF-L9IrPUYqizsnR37QsUwJW5xjob5vX8_DHjJOu1QS2Wdpa7Y_PSkXyX9jR75z3JHQO3paVIs
          groups: test-team
          file: app/build/outputs/apk/app.apk